# Generated by Django 2.2.28 on 2025-03-19 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YouHate', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
