# Generated by Django 2.2.28 on 2025-03-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouHate', '0004_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='disliked_by',
            field=models.ManyToManyField(blank=True, default=None, related_name='disliked_videos', to='YouHate.UserProfile'),
        ),
        migrations.AddField(
            model_name='video',
            name='liked_by',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked_videos', to='YouHate.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/profile_pictures/defaultPfp.jpg', upload_to='profile_pictures/'),
        ),
    ]
