# Generated by Django 2.2.28 on 2025-03-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouHate', '0005_auto_20250324_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/profile_pictures/blankProfile.png', upload_to='profile_pictures/'),
        ),
    ]
