# Generated by Django 2.2.28 on 2025-03-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YouHate', '0005_auto_20250324_2117'),
        ('YouHate', '0005_auto_20250324_1721'),
    ]

    operations = [
    ]
