# Generated by Django 2.2.28 on 2025-03-25 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YouHate', '0006_auto_20250325_1508'),
        ('YouHate', '0006_merge_20250325_1424'),
    ]

    operations = [
    ]
