# Generated by Django 2.2.28 on 2025-03-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouHate', '0006_merge_20250325_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/profile_pictures/blankProfile.png', upload_to='profile_pictures/'),
        ),
    ]
