# Generated by Django 2.2.28 on 2025-03-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_userprofile_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
